# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(283, 233)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_side = QtWidgets.QVBoxLayout()
        self.left_side.setObjectName("left_side")
        self.model_list = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.model_list.sizePolicy().hasHeightForWidth())
        self.model_list.setSizePolicy(sizePolicy)
        self.model_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.model_list.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.model_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.model_list.setObjectName("model_list")
        self.left_side.addWidget(self.model_list)
        self.horizontalLayout.addLayout(self.left_side)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.right_side = QtWidgets.QVBoxLayout()
        self.right_side.setObjectName("right_side")
        self.download_button = QtWidgets.QPushButton(Form)
        self.download_button.setObjectName("download_button")
        self.right_side.addWidget(self.download_button)
        self.stop_button = QtWidgets.QPushButton(Form)
        self.stop_button.setEnabled(True)
        self.stop_button.setObjectName("stop_button")
        self.right_side.addWidget(self.stop_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.right_side.addItem(spacerItem)
        self.apply_button = QtWidgets.QPushButton(Form)
        self.apply_button.setObjectName("apply_button")
        self.right_side.addWidget(self.apply_button)
        self.cancel_button = QtWidgets.QPushButton(Form)
        self.cancel_button.setObjectName("cancel_button")
        self.right_side.addWidget(self.cancel_button)
        self.horizontalLayout.addLayout(self.right_side)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Antibody Evolution Wizard Settings"))
        self.download_button.setText(_translate("Form", "Download Selected"))
        self.stop_button.setText(_translate("Form", "Stop Download"))
        self.apply_button.setText(_translate("Form", "Apply"))
        self.cancel_button.setText(_translate("Form", "Cancel"))
