name: pymol_antibody_evo
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy>=2.0
  - freetype
  - pyqt
  - python=3.10
  - libpng
  - glm
  - glew 
  - pyyaml
  - openmm
  - libnetcdf
  - pip
  - pip:
    - prodigy-prot==2.2.4
