models:
  - name: "esm1b"
    use: False
  - name: "esm1v1"
    use: False
  - name: "esm1v2"
    use: False
  - name: "esm1v3"
    use: False
  - name: "esm1v4"
    use: False
  - name: "esm1v5"
    use: False
  - name: "esm-msa"
    use: False
